### ISSUE TITLE
Question about release

### ISSUE THREAD

**Issue by kosirm** [pkavumba/html-annotator#6]
Hi, first of all congrats for brave project. I was waiting a long time, that someone will take on annotator development. Is there any chance that you will release this as minified javascript file? Because I have just a bunch of errors when I try to build it. Thank you again!

**Comment by pkavumba** [comment]
Yes will release a minified js file soon. Could you share some of the errors you are getting so we can address them in case someone is also facing the same

**Comment by pkavumba** [comment]
I have added the minified version. It is available in the `pkg/` directory
